export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
    <meta charset="utf-8">
    <title>McMain Puzzle Page</title>
    <base href="https://nusnaa.github.io/McMainPuzzle/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="/mcmain-logo.png">
  <link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.mcmain-puzzle[_ngcontent-ng-c2637971693]{display:grid;gap:3px;cursor:pointer;margin:5px;background-repeat:no-repeat}.mcmain-puzzle__tile[_ngcontent-ng-c2637971693]{background-image:url(/mcmain-logo.png);border:1px solid grey}.mcmain-puzzle__tile-empty[_ngcontent-ng-c2637971693]{background:#d3d3d3}</style></head>
  <body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
    <app-root ng-version="20.2.4" ngh="1" ng-server-context="ssg"><h1>Welcome to McMain Puzzle</h1><router-outlet></router-outlet><mcmain-puzzle _nghost-ng-c2637971693 ngh="0"><div _ngcontent-ng-c2637971693 class="mcmain-puzzle" style="grid-template-columns: repeat(4, 100px); grid-template-rows: repeat(4, 100px);"><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -0px -0px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -100px -0px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -200px -0px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -300px -0px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -0px -100px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -100px -100px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -200px -100px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -300px -100px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -0px -200px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -100px -200px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -200px -200px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -300px -200px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -0px -300px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -100px -300px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile" style="background-position: -200px -300px; background-size: 400px 400px;" jsaction="click:;"></div><div _ngcontent-ng-c2637971693 class="mcmain-puzzle__tile mcmain-puzzle__tile-empty" style="background-position: -300px -300px; background-size: 400px 400px;" jsaction="click:;"></div><!----></div><button _ngcontent-ng-c2637971693 jsaction="click:;">New Game</button></mcmain-puzzle><!----></app-root>
  <script src="main-5OY7VLXJ.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"2":"t0"},"c":{"2":[{"i":"t0","r":1,"x":16}]}},{"c":{"2":[{"i":"c2637971693","r":1}]}}]}</script></body></html>`;